[package]
name = "odin"
version = "1.5.3"
authors = ["mbround18"]
edition = "2021"
license = "BSD-3-Clause License"
description = "Valheim server manager"
readme = "README.md"
homepage = "https://github.com/mbround18/valheim-docker"
repository = "https://github.com/mbround18/valheim-docker"
keywords = ["cli", "valheim", "gameserver"]
categories = ["command-line-utilities"]
include = [
  "**/*.rs",
  "**/*.yaml",
  "Cargo.toml",
]


[[bin]]
name = "odin"
path = "main.rs"

[lib]
name = "odin"
path = "lib.rs"


[dependencies]
handlebars = "4"
dotenv = "0.15"
log = "0.4"
clap = { version = "2" , features = ["yaml"] }
which = "4.4.0"
serde = { version = "1.0", features = ["derive"], default_features = false  }
sysinfo = { version = "0.22.5", default_features = false }
serde_json = "1.0"
daemonize = "0.4"
tar = "0.4"
flate2 = "1.0"
inflections = "1.1.1"
md5 = "0.7"
reqwest = { version = "0.11", default_features = false, features = ["blocking", "json", "rustls-tls"] }
chrono = "0.4.23"
zip = { version = "0.6.3" }
fs_extra = "1.2.0"
glob = "0.3.0"
a2s = "0.5.1"
users = "0.11.0"

[dev-dependencies]
once_cell = "1"
rand = "0.8"
serial_test = "0.9.0"

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
features = ["run-for-all",	"precommit-hook", "run-cargo-fmt", "run-cargo-test", "run-cargo-clippy"]
