[package]
name = "odin"
version = "2.1.0"
authors = ["mbround18"]
edition = "2021"
license = "BSD-3-Clause License"
description = "Valheim server manager"
readme = "README.md"
homepage = "https://github.com/mbround18/valheim-docker"
repository = "https://github.com/mbround18/valheim-docker"
keywords = ["cli", "valheim", "gameserver"]
categories = ["command-line-utilities"]
include = [
  "**/*.rs",
  "**/*.yaml",
  "Cargo.toml",
]


[[bin]]
name = "odin"
path = "main.rs"

[lib]
name = "odin"
path = "lib.rs"

[build-dependencies]
cc = "1"

[dependencies]
handlebars = "6.3.1"
dotenv = "0.15"
log = "0.4.25"
clap = { version = "4.5.28", features = [ "derive", "env" ] }
which = "*"
serde = { version = "1.0.217", features = ["derive"], default-features = false  }
sysinfo = { version = "0.33.1" }
serde_json = "1.0.138"
daemonize = "0.5.0"
tar = "0.4.43"
flate2 = "1.0.35"
inflections = "1.1.1"
md5 = "0.7"
reqwest = { version = "0.12.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
chrono = "0.4.39"
zip = { version = "2.2.2" }
fs_extra = "1.3"
glob = "0.3"
a2s = "0.5.2"
serde_with = "3.12.0"
regex = "1.11.1"
tokio = { version = "1", features = ["full"] }
notify = "8.0.0"
json-patch = "*"
cached = "0"
anyhow = "1.0.95"

[dev-dependencies]
once_cell = "1.20.3"
rand = "0.9.0"
serial_test = "3.2.0"
mockito = "1.6.1"
lazy_static = "1.5.0"
test-case = "3"
mockall = "0"



[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
features = ["run-for-all",	"precommit-hook", "run-cargo-fmt", "run-cargo-test", "run-cargo-clippy"]
