[package]
name = "odin"
version = "2.1.0"
authors = ["mbround18"]
edition = "2021"
license = "BSD-3-Clause License"
description = "Valheim server manager"
readme = "README.md"
homepage = "https://github.com/mbround18/valheim-docker"
repository = "https://github.com/mbround18/valheim-docker"
keywords = ["cli", "valheim", "gameserver"]
categories = ["command-line-utilities"]
include = [
  "**/*.rs",
  "**/*.yaml",
  "Cargo.toml",
]


[[bin]]
name = "odin"
path = "main.rs"

[lib]
name = "odin"
path = "lib.rs"


[dependencies]
handlebars = "5.1.2"
dotenv = "0.15"
log = "0.4.21"
clap = { version = "4.5.4", features = [ "derive", "env" ] }
which = "*"
serde = { version = "1.0.200", features = ["derive"], default_features = false  }
sysinfo = { version = "0.30.11", default_features = false }
serde_json = "1.0.116"
daemonize = "0.5.0"
tar = "0.4.40"
flate2 = "1.0.30"
inflections = "1.1.1"
md5 = "0.7"
reqwest = { version = "0.12.4", default_features = false, features = ["blocking", "json", "rustls-tls"] }
chrono = "0.4.38"
zip = { version = "1.1.3" }
fs_extra = "1.3"
glob = "0.3"
a2s = "0.5.2"
serde_with = "3.8.1"
regex = "1.10.4"


[dev-dependencies]
once_cell = "1.19.0"
rand = "0.8.5"
serial_test = "3.1.1"
mockito = "1.4.0"
lazy_static = "1.4.0"

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
features = ["run-for-all",	"precommit-hook", "run-cargo-fmt", "run-cargo-test", "run-cargo-clippy"]
