name: Docker Build

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix: 
        image: [odin, valheim]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build ${{ matrix.image }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.${{ matrix.image }}
          push: false
          tags: mbround18/${{ matrix.image }}:latest  
          build-args: |
            "GITHUB_SHA=${GITHUB_SHA}"
            "GITHUB_REF=${GITHUB_REF}"
            "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
      
      - name: Finalization
        run: echo "Finalized"
        

