name: Release

on: [push]

env:
  GH_TOKEN: "${{ secrets.GH_TOKEN }}"

jobs:
  release:
    name: Release Train WooohWoooohh
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@1.0.5
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        with:
          branch: main
          access-token: ${{ secrets.GH_TOKEN }}

      - name: Create Release
        run: |
          yarn auto shipit

      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@1.0.5
        # Force to always run this step to ensure "include administrators" is always turned back on
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        with:
          branch: main
          access-token: ${{ secrets.GH_TOKEN }}
