name: Release

on: [push]

env:
  GH_TOKEN: "${{ secrets.GH_TOKEN }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release Train WooohWoooohh
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup | Rust | Nightly
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          components: clippy rustfmt

      - uses: davidB/rust-cargo-make@v1
        name: Install Cargo Make

      - uses: actions/cache@v3
        name: Cache Cargo Files
        with:
          path: |
            target/release
            target/debug
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Release
        run: cargo make -p production release

      - uses: vimtor/action-zip@v1
        with:
          files: target/release/odin target/release/huginn
          dest: tmp/bundle.zip

      - name: Auto Release Tool by Intuit
        uses: mbround18/auto@v1.5.0
        with:
          token: ${{ secrets.GH_TOKEN }}
