name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NAME: "Rust Test"
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up Rust with the stable toolchain
      - name: Setup | Rust | Stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy rustfmt

      # Cache Cargo build files to speed up builds
      - uses: actions/cache@v4
        name: Cache Cargo Files
        with:
          path: |
            target/release
            target/debug
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      # Build the Rust project
      - name: Build
        run: cargo build --verbose

      # Run tests
      - name: Run tests
        run: cargo test --verbose

      # Check formatting
      - name: Lint
        run: cargo fmt -- --check
